FROM grafana/grafana:7.5.17-ubuntu

RUN wget -c https://github.com/HadesArchitect/GrafanaCassandraDatasource/releases/download/0.5.0/cassandra-datasource-0.5.0.tar.gz -O - | tar xz -C /var/lib/grafana/plugins
